{
  config,
  pkgs,
  pkgs-unstable,
  lib,
  niriEnabled,
  ...
}: {
  environment.systemPackages = with pkgs;
    [
      kitty
      nerd-fonts.jetbrains-mono
      font-awesome
      vimix-cursors
      wl-clipboard
      pavucontrol
      brightnessctl
      arp-scan
      tailscale
      libnotify
      dnsutils
      clang-tools
      lua-language-server
      pyright
      nodePackages.typescript-language-server
      nodePackages.eslint
      emmet-language-server
      simple-completion-language-server
      uv
      fish
      kdePackages.kdenlive
      bzmenu
      nodejs
      nil
      alejandra
      statix
      slack
      github-copilot-cli
      cloudflared
      ncdu
      hyprshot
      discord
      cmatrix
      wiremix
      powertop
      nautilus
      tree-sitter
      gcc
      gnumake
      pkgs-unstable.neovim
      svelte-language-server
    ]
    ++ lib.optionals niriEnabled [
      niri
    ];
}
